name: cicd for ai-app

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t murtaza007/hts-ai:latest -t murtaza007/hts-ai:${{ github.sha }} .
          docker push murtaza007/hts-ai:latest
          docker push murtaza007/hts-ai:${{ github.sha }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image..."
            docker pull murtaza007/hts-ai:${{ github.sha }}

            echo "Freeing up port 5000..."
            sudo fuser -k 5000/tcp || true

            echo "Stopping and removing old container..."
            docker stop hts-ai-cont || true
            docker rm hts-ai-cont || true

            echo "Running new container..."
            docker run -d -p 5000:5000 --name hts-ai-cont --restart unless-stopped murtaza007/hts-ai:${{ github.sha }}

            echo "Restarting Nginx..."
            sudo systemctl restart nginx

            echo "✅ Deployment successful"